### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by jpiquot** [microsoft/vs-dapr#10]
I have the following error when trying to install the extension :

![image](https://github.com/microsoft/vs-dapr/assets/6775094/00f4f1f2-db4d-4c2a-ad52-c799a3be84d7)

**Comment by philliphoff** [comment]
@jpiquot A new build (`0.1.0102.1`) has been generated and links updated.

> [!IMPORTANT]
> This build (and onward) requires Visual Studio 2022 17.9 Preview 2.

**Comment by christophwille** [comment]
@philliphoff could you please maintain a simple "Chang log" issue so that we could have a general idea what changed between available builds? (like requirements, features expected to work, ...)

**Comment by philliphoff** [comment]
@christophwille Fair point; I've started a *very* basic [changelog](https://github.com/microsoft/vs-dapr?tab=readme-ov-file#changelog).

**Comment by philliphoff** [comment]
(Closing as completed.)

**Comment by philliphoff** [comment]
(Additional note: the extension is now in the VS Marketplace and the "unofficial" gallery has been shut down.)
