### ISSUE TITLE
Unable to specify custom httpPort and grpcPort?

### ISSUE THREAD

**Issue by tpankake-insight** [microsoft/vs-dapr#19]
I have tried adding `grpcPort:` and `httpPort:` to the dapr.yaml file for each of my projects with a specific port number. However, when I start my services through VS, I see the `dapr run` command does not include `--http-port` or `--grpc-port` arguments and the ports are randomly assigned and change each time I restart debugging.  I need to be able to predict my http and grpc dapr ports. Is there a yaml syntax that I'm not seeing?  Or is this a known issue?

**Comment by philliphoff** [comment]
@tpankake-insight Per the [spec](https://docs.dapr.io/developing-applications/local-development/multi-app-dapr-run/multi-app-template/#template-properties), the Dapr run file uses the somewhat more unwieldy `daprGRPCPort` and `daprHTTPPort` properties to indicate the gRPC and HTTP ports used by the Dapr sidecar.

**Comment by philliphoff** [comment]
(Closing as verified that VS was abiding by the Dapr run file spec.)
