### ISSUE TITLE
Localization bug?

### ISSUE THREAD

**Issue by WhitWaldo** [microsoft/vs-dapr#6]
I was just setting up a simple Dapr example - a console app with all of four lines of code and the Dapr package installed. I right clicked the solution and under Add, I see the following:

![image](https://github.com/microsoft/vs-dapr/assets/2238529/db92d9a7-ef1d-451c-89ba-8c58559edaa9)

**Comment by philliphoff** [comment]
@WhitWaldo Well, that's not what I'd expect to see.  Which version of VS are you using, and which version of the Dapr extension?

**Comment by WhitWaldo** [comment]
VS 17.7.5 and extension 0.1.1013.1 (though just saw the upgrade, so I'll be installing that later today).

I did click on one of the items and it generated the file properly, but yeah, didn't expect to see so many options!

**Comment by philliphoff** [comment]
Yeah, sorry, for several reasons I had to drop VS 17.7 as a target and force users to move to 17.8 even though it's still in preview.

**Comment by philliphoff** [comment]
Closing as resolved (by way of using the newer VS builds).
